### PR TITLE
drop to alpine 18 to avoid lib issues with wasmvm

### PR DESCRIPTION
**Pull request by ash-burnt**

### CODE REVIEW

**Comment by ash-burnt** [comment]
related to:
https://github.com/wasmerio/wasmer/issues/4488
https://github.com/CosmWasm/wasmvm/issues/523

**Comment by ash-burnt** [comment]
closes https://github.com/burnt-labs/xion/issues/180

**Comment by bert2002** [comment]
Log from the beginning 
```
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | 4:25AM INF indexed block events height=6953914 module=txindex
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | 4:25AM INF minted coins from module account amount=1809286uxion from=mint module=x/bank
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | 4:25AM INF executed block height=6953915 module=state num_invalid_txs=0 num_valid_txs=2
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | 4:25AM INF commit synced commit=436F6D6D697449447B5B3233372031313720323230203230352031343320313234203234302039392033322039203138312031383320313437203534203135302033322031393320323134203133332030203231342031333520313339203131382031393420363120393320323435203339203737203430203133315D3A3641314242427D module=server
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | 4:25AM INF committed state app_hash=ED75DCCD8F7CF0632009B5B793369620C1D68500D6878B76C23D5DF5274D2883 height=6953915 module=state num_txs=2
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | 4:25AM INF indexed block events height=6953915 module=txindex
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | 4:25AM INF minted coins from module account amount=1809286uxion from=mint module=x/bank
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | SIGABRT: abort
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | PC=0x2d0ec61 m=13 sigcode=18446744073709551610
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | signal arrived during cgo execution
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | goroutine 73 [syscall]:
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.cgocall(0x22941a0, 0xc0031985d8)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/cgocall.go:157 +0x4b fp=0xc0031985b0 sp=0xc003198578 pc=0x456f4b
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmvm/internal/api._C2func_save_wasm(0x7f9504f17040, {0x0, 0xc016eee000, 0x2dace}, 0x0, 0xc002409a60)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         _cgo_gotypes.go:662 +0x65 fp=0xc0031985d8 sp=0xc0031985b0 pc=0x165bb65
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmvm/internal/api.StoreCode.func1({0x57a6810?}, {0x58?, 0xc016eee000?, 0x0?}, 0x0?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/CosmWasm/wasmvm@v1.5.2/internal/api/lib.go:65 +0x97 fp=0xc003198670 sp=0xc0031985d8 pc=0x165ebf7
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmvm/internal/api.StoreCode({0x1?}, {0xc016eee000?, 0x0?, 0x14?})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/CosmWasm/wasmvm@v1.5.2/internal/api/lib.go:65 +0x11e fp=0xc003198738 sp=0xc003198670 pc=0x165ea3e
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmvm.(*VM).StoreCode(0xc01510a000?, {0xc016eee000?, 0x331a9e6?, 0xc8000?})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/CosmWasm/wasmvm@v1.5.2/lib.go:60 +0x1b fp=0xc003198768 sp=0xc003198738 pc=0x166b49b
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.create({{0x3eee9c8, 0xc000d21230}, {0x3f2fc70, 0xc00125eda0}, {0x3ef37a0, 0xc001237b30}, {0x3ee3dc0, 0xc000c5c960}, {0x3ee3100, 0xc000e0b2a0}, ...}, ...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:181 +0x62e fp=0xc003199e18 sp=0xc003198768 pc=0x1f9006e
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmd/x/wasm/keeper.msgServer.StoreCode({0x45e0da?}, {0x3f0ecd0, 0xc01c80c000}, 0xc01c82c3c0)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/msg_server.go:38 +0x225 fp=0xc00319a600 sp=0xc003199e18 pc=0x1fa5fa5
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmd/x/wasm/keeper.(*msgServer).StoreCode(0x45dba5?, {0x3f0ecd0?, 0xc01c80c000?}, 0x32e33a0?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         <autogenerated>:1 +0x2e fp=0xc00319a630 sp=0xc00319a600 pc=0x1fc18ee
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmd/x/wasm/types._Msg_StoreCode_Handler.func1({0x3f0ecd0, 0xc01c80c000}, {0x32450a0?, 0xc01c82c3c0})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/CosmWasm/wasmd@v0.45.0/x/wasm/types/tx.pb.go:2209 +0x72 fp=0xc00319a670 sp=0xc00319a630 pc=0x1728452
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x3f0e758, 0xc0127b9600}, {0xc00319a708?, 0x45dba5?}, 0x2a0?, 0xc0205344b0)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/baseapp/msg_service_router.go:118 +0x93 fp=0xc00319a6c0 sp=0xc00319a670 pc=0x11e4b33
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/CosmWasm/wasmd/x/wasm/types._Msg_StoreCode_Handler({0x32303a0?, 0xc001399940}, {0x3f0e758, 0xc0127b9600}, 0x39d1a78, 0xc0024099e0)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/CosmWasm/wasmd@v0.45.0/x/wasm/types/tx.pb.go:2211 +0x135 fp=0xc00319a718 sp=0xc00319a6c0 pc=0x1728335
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x3f0ecd0, 0xc01e096a50}, {0x3f243e0, 0xc01fde0980}, {{0xb, 0x0}, {0xc00e0894a0, 0xe}, 0x6a1bbc, {0x1641a8e4, ...}, ...}, ...}, ...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/baseapp/msg_service_router.go:139 +0x343 fp=0xc00319b240 sp=0xc00319a718 pc=0x11e48c3
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x3f0ecd0, 0xc01e096a50}, {0x3f243e0, 0xc01fde0980}, {{0xb, 0x0}, {0xc00e0894a0, 0xe}, 0x6a1bbc, ...}, ...}, ...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/baseapp/baseapp.go:806 +0x271 fp=0xc00319b7a8 sp=0xc00319b240 pc=0x11e1211
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000e0ad20, 0x3, {0xc006592000, 0xf69f, 0xf69f})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/baseapp/baseapp.go:749 +0xe65 fp=0xc00319e9c0 sp=0xc00319b7a8 pc=0x11e02c5
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(0xc000e0ad20, {{0xc006592000?, 0xc00319ecf0?, 0x4e568e?}})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/baseapp/abci.go:413 +0x178 fp=0xc00319ec10 sp=0xc00319e9c0 pc=0x11d70d8
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/burnt-labs/xion/app.(*WasmApp).DeliverTx(0x1?, {{0xc006592000?, 0x20?, 0x20?}})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         <autogenerated>:1 +0x68 fp=0xc00319ed30 sp=0xc00319ec10 pc=0x2276b88
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cometbft/cometbft/abci/client.(*localClient).DeliverTxAsync(0xc0000f4d80, {{0xc006592000?, 0x0?, 0x0?}})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/abci/client/local_client.go:82 +0xf9 fp=0xc00319eeb8 sp=0xc00319ed30 pc=0xff3ed9
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cometbft/cometbft/proxy.(*appConnConsensus).DeliverTxAsync(0xc002a182b8, {{0xc006592000?, 0x20?, 0xb?}})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/proxy/app_conn.go:106 +0x162 fp=0xc00319ef58 sp=0xc00319eeb8 pc=0xffbe42
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cometbft/cometbft/state.execBlockOnProxyApp({0x3f0e3d8?, 0xc000d1cb30}, {0x3f20960, 0xc002a182b8}, 0xc00a99de00, {0x3f249c8, 0xc0038fcb40}, 0x6a1bbb?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/state/execution.go:376 +0x6b6 fp=0xc00319f380 sp=0xc00319ef58 pc=0x1002e56
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc006244f3a, 0x6}}, {0xc006244f50, 0xe}, 0x1, 0x6a1bbb, {{0xc0218a9b20, ...}, ...}, ...}, ...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/state/execution.go:197 +0x165 fp=0xc00319f850 sp=0xc00319f380 pc=0x10014c5
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc000da4700, 0x0)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/blocksync/reactor.go:405 +0xb5a fp=0xc00319ffc0 sp=0xc00319f850 pc=0x10af65a
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart.func1()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/blocksync/reactor.go:125 +0x25 fp=0xc00319ffe0 sp=0xc00319ffc0 pc=0x10adb05
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goexit()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc00319ffe8 sp=0xc00319ffe0 pc=0x4c16a1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 24
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cometbft/cometbft@v0.37.4/blocksync/reactor.go:125 +0x6e
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | goroutine 1 [chan receive, 2 minutes]:
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.gopark(0xc0026054d8?, 0xad7725?, 0x1?, 0x4b?, 0xc002605550?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc0026054c0 sp=0xc0026054a0 pc=0x48df0e
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.chanrecv(0xc008f521e0, 0xc002605588, 0x1)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/chan.go:583 +0x3cd fp=0xc002605538 sp=0xc0026054c0 pc=0x45956d
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.chanrecv1(0xc008f521e0?, 0xc002605598?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/chan.go:442 +0x12 fp=0xc002605560 sp=0xc002605538 pc=0x459172
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/server.WaitForQuitSignals()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/server/util.go:391 +0x86 fp=0xc0026055c8 sp=0xc002605560 pc=0x13427c6
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc001191260, 0xc0000e9600)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/server/start.go:627 +0x2f2 fp=0xc0026056b0 sp=0xc0026055c8 pc=0x133f172
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001262f00?, {0xc000dd3f20?, 0x0?, 0x3?})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/server/start.go:152 +0x2c5 fp=0xc002605c18 sp=0xc0026056b0 pc=0x133b465
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/spf13/cobra.(*Command).execute(0xc001308000, {0xc000dd3e60, 0x3, 0x3})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc fp=0xc002605db8 sp=0xc002605c18 pc=0xb2265c
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/spf13/cobra.(*Command).ExecuteC(0xc00120ec00)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff fp=0xc002605e90 sp=0xc002605db8 pc=0xb22f1f
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/spf13/cobra.(*Command).Execute(...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/spf13/cobra@v1.8.0/command.go:1039
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/spf13/cobra.(*Command).ExecuteContext(...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/spf13/cobra@v1.8.0/command.go:1032
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2295ac0?, {0x0, 0x0}, {0xc000f90390, 0x12})
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/cosmos/cosmos-sdk@v0.47.10/server/cmd/execute.go:33 +0x171 fp=0xc002605f08 sp=0xc002605e90 pc=0x13446b1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | main.main()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         github.com/burnt-labs/xion/cmd/xiond/main.go:15 +0x2a fp=0xc002605f40 sp=0xc002605f08 pc=0x229078a
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.main()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:267 +0x2bb fp=0xc002605fe0 sp=0xc002605f40 pc=0x48da9b
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goexit()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc002605fe8 sp=0xc002605fe0 pc=0x4c16a1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | goroutine 2 [force gc (idle), 2 minutes]:
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc000072fa8 sp=0xc000072f88 pc=0x48df0e
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goparkunlock(...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:404
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.forcegchelper()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:322 +0xb3 fp=0xc000072fe0 sp=0xc000072fa8 pc=0x48dd73
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goexit()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x4c16a1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | created by runtime.init.6 in goroutine 1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:310 +0x1a
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | goroutine 3 [GC sweep wait]:
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc000073778 sp=0xc000073758 pc=0x48df0e
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goparkunlock(...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:404
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.bgsweep(0x0?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/mgcsweep.go:321 +0xdf fp=0xc0000737c8 sp=0xc000073778 pc=0x477fff
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.gcenable.func1()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/mgc.go:200 +0x25 fp=0xc0000737e0 sp=0xc0000737c8 pc=0x46d165
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goexit()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x4c16a1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | created by runtime.gcenable in goroutine 1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/mgc.go:200 +0x66
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | goroutine 4 [GC scavenge wait]:
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.gopark(0x58efd80?, 0x17ac9aa?, 0x0?, 0x0?, 0x0?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:398 +0xce fp=0xc000073f70 sp=0xc000073f50 pc=0x48df0e
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goparkunlock(...)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/proc.go:404
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.(*scavengerState).park(0x58efd80)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/mgcscavenge.go:425 +0x49 fp=0xc000073fa0 sp=0xc000073f70 pc=0x475889
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.bgscavenge(0x0?)
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/mgcscavenge.go:658 +0x59 fp=0xc000073fc8 sp=0xc000073fa0 pc=0x475e39
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.gcenable.func2()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/mgc.go:201 +0x25 fp=0xc000073fe0 sp=0xc000073fc8 pc=0x46d105
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | runtime.goexit()
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/asm_amd64.s:1650 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x4c16a1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  | created by runtime.gcenable in goroutine 1
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |         runtime/mgc.go:201 +0xa5
Mar 19 04:25:28 node xion[140770]: xion-cosmos-1  |
```

**Review by froch — APPROVED** [review]
✅  Approved. Will keep an eye out, hopefully this grid from https://github.com/wasmerio/wasmer/issues/4488 holds true

312177219-44217981-9125-4c0e-ba9d-98cdc5444e33

**Pull request merged**
